// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiPeTtf_AKKkSZysB2XQdT0O7h3GLh3PQ',
    appId: '1:1069207850415:android:38bc3638eb32f9bf50f35a',
    messagingSenderId: '600806890780',
    projectId: 'beauty-salon-5d6bb',
    storageBucket: 'beauty-salon-5d6bb.appspot.com',
    // measurementId: 'G-HYLR3KGRNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-SiC4N22BAmTtLoEZMcTOEkF7JhE9Xbk',
    appId: '1:677282971625:android:55017795bb2915dc025578',
    messagingSenderId: '677282971625',
    projectId: 'auth-task-b0ae5',
    storageBucket: 'auth-task-b0ae5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtKOS2h9xkrqi_2cZionSLCqvAhYc-Yss',
    appId: '1:816831984722:ios:5a00c0695b237284749b8b',
    messagingSenderId: '816831984722',
    projectId: 'antonx-flutter-template',
    storageBucket: 'antonx-flutter-template.appspot.com',
    iosClientId:
        '816831984722-rnmhv8pt2rrq4b3tpi1i6o72rddqo074.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAntonxBoilerplate',
  );
}
